In [2]:
struct Point
    x::Float64
    y::Float64
end

p = Point(1.2, 2.3)

Point(1.2, 2.3)

In [3]:
p.x

1.2

In [4]:
p.y

2.3

In [5]:
p

Point(1.2, 2.3)

In [6]:
Point(1, 2)

Point(1.0, 2.0)

In [7]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [9]:
ys = [y^2 for y in 1:10]

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [12]:
for (i,y) in enumerate(ys)
    @show (i,y)
end

(i, y) = (1, 1)
(i, y) = (2, 4)
(i, y) = (3, 9)
(i, y) = (4, 16)
(i, y) = (5, 25)
(i, y) = (6, 36)
(i, y) = (7, 49)
(i, y) = (8, 64)
(i, y) = (9, 81)
(i, y) = (10, 100)


In [13]:
map(ys) do y
    return sqrt(y)
end

10-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

In [14]:
floor(Int, 3.14)

3

In [15]:
ceil(Int, 3.14)

4

In [16]:
Float64(22)

22.0

In [17]:
22/7

3.142857142857143

In [18]:
22//7

22//7

In [19]:
typeof(22//7)

Rational{Int64}

In [20]:
dump(22//7)

Rational{Int64}
  num: Int64 22
  den: Int64 7


In [21]:
pi = 22//7
pi.num

22

In [22]:
pi.den

7

In [23]:
22//7 * 7//32

11//16

In [24]:
[i//10 for i in 1:10]

10-element Vector{Rational{Int64}}:
 1//10
 1//5
 3//10
 2//5
 1//2
 3//5
 7//10
 4//5
 9//10
 1//1

In [25]:
zeros(Rational{Int64}, 10,10)

10×10 Matrix{Rational{Int64}}:
 0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1
 0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1
 0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1
 0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1
 0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1
 0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1
 0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1
 0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1
 0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1
 0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1  0//1

In [29]:
A = [1 1; 1 0]

2×2 Matrix{Int64}:
 1  1
 1  0

In [30]:
map(1:10) do i
    A^i
end


10-element Vector{Matrix{Int64}}:
 [1 1; 1 0]
 [2 1; 1 1]
 [3 2; 2 1]
 [5 3; 3 2]
 [8 5; 5 3]
 [13 8; 8 5]
 [21 13; 13 8]
 [34 21; 21 13]
 [55 34; 34 21]
 [89 55; 55 34]

In [33]:
(A^6)[:,1]

2-element Vector{Int64}:
 13
  8

In [34]:
(A^6)[3]

8

In [35]:
function f(x)
    return A^x
end

f (generic function with 1 method)

In [36]:
g(x) = A^x

g (generic function with 1 method)

In [37]:
g == f

false

In [38]:
map(f, 1:10)

10-element Vector{Matrix{Int64}}:
 [1 1; 1 0]
 [2 1; 1 1]
 [3 2; 2 1]
 [5 3; 3 2]
 [8 5; 5 3]
 [13 8; 8 5]
 [21 13; 13 8]
 [34 21; 21 13]
 [55 34; 34 21]
 [89 55; 55 34]

In [40]:
pₜ = (x=1, y=2)

(x = 1, y = 2)

In [41]:
typeof(pₜ)

NamedTuple{(:x, :y), Tuple{Int64, Int64}}

In [42]:
pₜ[1] == pₜ.x

true